---
### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /comlab ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "JSG"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#BF5700'
  white:     '#005F86'
  blue:      '#43695B'
  green:     '#F2A900'
  purple:    '#D6D2C4'
  orange:    '#382F2D'
  turquoise: '#333F48'
  
kramdown:
  auto_ids:  false

# Prose configuration
prose:
  media: "comlab/img/"
  siteurl: "comlab/"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "insert title here"
      - name: "description"
        field:
          label: "meta-description"
          element: "text"
          value: "meta-description"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          value: "tags"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "insert title here"
