---
### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: "/comlab" ## disables post output
baseurl: "http://apapendieck.github.io/comlab"
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Jackson School Geoscientific Communication Lab"
keywords:    "Geosciences, Writing, Communication, Open Science, Multiliteracies, Curriculum, Consultation"
description: "Home page of the Jackson Schools Writer-in-Residence and Geoscientific Communication Lab"
source_link: "https://github.com/apapendieck/comlab"
favicon:     "img/badgesci-comm-logo-o.png"
touch_icon:  "img/badgesci-comm-logo-o.png"
google_analytics_key: UA-49607422-1


### template colors, used site-wide via css ###
colors:
  black: '#000000'
  white: '#FFFFFF'
  orange: '#BF5700'
  gray: '#333F48'
  darkb: '#005F86'
  green: '#43695B'
  yellow: '#F2A900'
  brown: '#382F2D'
  beige: '#D6D2C4'
  lightb: '#E8EAF6'
  
kramdown:
  auto_ids:  false
